version: '3.8'
services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    ports:
      - '5434:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_test
    ports:
      - '5435:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local